### ISSUE TITLE
"undefined" in title of many items in scripting.com/river.html

### ISSUE THREAD

**Issue by richb-hanover** [scripting/river5#33]
I don't know if this is the right place to report this, but many of the items in scripting.com/river.html have "undefined ([Feed]())" as the "source" of the item. I append a recent screen shot.

Is this expected? (Everything else seems to work fine.) Thanks.

<img width="725" alt="image" src="https://user-images.githubusercontent.com/1094930/189503162-a92be967-5b1c-487c-b51c-7f39b6195158.png">

**Comment by scripting** [comment]
@richb-hanover -- yes of course I've seen that too. There's obviously a problem in there. But rather than try to fix it now, we're on the verge of switching over to a new feed management system, and it does not have this problem and has lots of other features. But thanks for the report in the meantime.

**Comment by richb-hanover** [comment]
A perfect answer. Good luck switching to the new system. Thanks.

**Comment by scripting** [comment]
Here's the news..

http://scripting.com/2022/10/04/142201.html?title=feedland

Dave
